#!/usr/bin/bash

# Corrigir problema da rede
# Instalar font-awesome
# Instalar xampp
# Pegar backup e por wallpaper
# adicionar chave do speedricer

add-apt-repository ppa:kgilmer/speed-ricer

apt update

apt install -y fish aptitude vlc libreoffice firefox nodejs default-jdk vim-gtk3 polybar fonts-noto breeze dolphin network-manager feh gimp inkscape qpdfview pavucontrol pulseaudio ftp filezilla aria2 putty pulsemixer htop unzip unrar lxappearance git obs-studio youtube-dl i3-wm lightdm lightdm-gtk-greeter suckless-tools xbacklight xfce4-screenshooter xfce4-terminal xfce4-clipman breeze-gtk-theme  

snap install telegram-desktop discord beekeeper-studio code
snap install code --classic
