require('plugins')
require('settings')

require('mini.ai').setup()
require('mini.animate').setup()
require('mini.cursorword').setup()
require('mini.indentscope').setup()
require('mini.jump').setup()
require('mini.statusline').setup()
require('mini.surround').setup()
