
#######
# Env Vars
#######

export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
export DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock"
export PATH="/opt/homebrew/opt/openjdk/bin:/Users/eduardo.paz/.local/bin:$PATH"
export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE="${HOME}/.colima/default/docker.sock"
export TESTCONTAINERS_RYUK_DISABLED=true
export ZSH="$HOME/.oh-my-zsh"
. ~/.asdf/plugins/java/set-java-home.zsh

#######
# Functions
#######

function qli-db() {
    local database_name="$1"
    qli database get "$database_name" --ttl=48h
}

function notify() {
    osascript -e 'display notification "Slow command finished already." with title "Good News FY" sound name "MGS"'
}

function help() {
    bash -c "${@} --help" | less
}

#######
# Aliases
#######

alias b='bat'
alias bi='brew install'
alias bug='brew upgrade -g'
alias buni='brew uninstall'
alias cp='cp -vi'
alias e='eza -hF'
alias ea='eza -haF'
alias eal='eza -halF'
alias el='eza -hlF'
alias glom='git pull origin master'
alias glor='git pull origin'
alias glpr='gl --prune'
alias grhf='git reset --hard origin/forno'
alias grhm='git reset --hard origin/master'
alias gs='git status'
alias gw='gradle'
alias mv='mv -vi'
alias ntest='npm run test-unit --'
alias pip='pip3'
alias python=python3
alias qli-db-list='qli database list | less'
alias rg='rg -S'
alias rm='rm -vi'
alias v='vim'

#######
# Plugins
#######

plugins=(
	aliases
	asdf
	brew
	colored-man-pages
	cp
	dirhistory
	gh
	git
	gradle
	history-substring-search
	vi-mode
	zsh-autosuggestions
	zsh-syntax-highlighting
)

#######
# Setups
#######

# Brew
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

# Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Starship
eval "$(starship init zsh)"

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/eduardo.paz/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

## [Completion]
## Completion scripts setup. Remove the following line to uninstall
[[ -f /Users/eduardo.paz/.dart-cli-completion/zsh-config.zsh ]] && . /Users/eduardo.paz/.dart-cli-completion/zsh-config.zsh || true
## [/Completion]

