#######
# Env Vars
#######

export CPPFLAGS="-I/opt/homebrew/opt/openjdk/include"
export CPPFLAGS="-I/opt/homebrew/opt/ruby/include"
export DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock"
export LDFLAGS="-L/opt/homebrew/opt/ruby/lib"
export PATH="/opt/homebrew/opt/openjdk/bin:/Users/eduardo.paz/.local/bin:/opt/homebrew/lib/ruby/gems/3.3.0:/opt/homebrew/lib/ruby/gems/3.3.0/bin:$PATH"
export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE="${HOME}/.colima/default/docker.sock"
export TESTCONTAINERS_RYUK_DISABLED=true
export ZSH="$HOME/.oh-my-zsh"

. ~/.asdf/plugins/java/set-java-home.zsh



# gateway

export APP_DB_URI=jdbc:postgresql://postgres.dev.quintoandar.com.br:5432/event_gateway
export APP_DB_USERNAME=quintoandar
export APP_DB_PASSWORD=quintoandar
export APP_DEPLOYMENT_ENV=local
export HOT_RELOAD=true
export FLYWAY_PASSWORD=quintoandar
export FLYWAY_USER=quintoandar
export FLYWAY_HOST=localhost
export KAFKA_BOOTSTRAP_SERVER=localhost:9092
export KAFKA_CLIENT_ID=a
export KAFKA_CLIENT_SECRET=a
export KAFKA_TOPIC_EVENT_GATEWAY=EventGatewayInternalBus
export KAFKA_TOPIC_CDP=CDPInternalBus
export COMMS_CONSOLE_PUBLIC_AMPLITUDE_KEY=c1080b612f6a0176a0a3857eb33af85e
export AWS_ACCESS_KEY_ID=test
export AWS_SECRET_ACCESS_KEY=test
export AWS_DEFAULT_REGION=us-east-1
export AWS_ENDPOINT_URL=http://localhost:4566


#######
# Functions
#######

function qli-db() {
    local database_name="$1"
    qli database get "$database_name" --ttl=48h
}

function gw-kotest() {
    kotest_filter_specs="$1" gw test
}

function notify() {
    osascript -e 'display notification "Slow command finished already." with title "Good News FY" sound name "MGS"'
}

function help() {
    bash -c "${@} --help" | less
}

#######
# Aliases
#######

alias b='bat'
alias bi='brew install'
alias bug='brew upgrade -g'
alias buni='brew uninstall'
alias cp='cp -vi'
alias e='eza -hF'
alias ea='eza -haF'
alias eal='eza -halF'
alias el='eza -hlF'
alias glom='git pull origin master'
alias glor='git pull origin'
alias glpr='gl --prune'
alias grhf='git reset --hard origin/forno'
alias grhm='git reset --hard origin/master'
alias gs='git status'
alias gw='gradle'
alias mv='mv -vi'
alias ntest='npm run test-unit --'
alias pip='pip3'
alias python=python3
alias qli-db-list='qli database list | less'
alias rg='rg -S'
alias rm='rm -vi'
alias v='vim'

#######
# Plugins
#######

plugins=(
	aliases
	asdf
	brew
	colored-man-pages
	cp
	dirhistory
	gh
	git
	gradle
	history-substring-search
	vi-mode
	zsh-autosuggestions
	zsh-syntax-highlighting
)

#######
# Setups
#######

# Brew
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

# Oh My Zsh
source $ZSH/oh-my-zsh.sh

# Starship
eval "$(starship init zsh)"

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
export PATH="/Users/eduardo.paz/.rd/bin:$PATH"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

## [Completion]
## Completion scripts setup. Remove the following line to uninstall
[[ -f /Users/eduardo.paz/.dart-cli-completion/zsh-config.zsh ]] && . /Users/eduardo.paz/.dart-cli-completion/zsh-config.zsh || true
## [/Completion]

