#!/usr/bin/bash

# Variables declarations
TERMINAL_COMMAND="alacritty --command"

declare -A PATH_CONFIG

PATH_CONFIG[config]=$PATH_CONFIG
PATH_CONFIG[alacritty]=$PATH_ALACRITTY
PATH_CONFIG[i3]=$PATH_I3
PATH_CONFIG[neovim]=$PATH_NEOVIM
PATH_CONFIG[picom]=$PATH_PICOM
PATH_CONFIG[fish]=$PATH_FISH
PATH_CONFIG[vars]=$PATH_VARS


# It prints per line the indexes of $PATH_CONFIG
# to finally gets a $SELECTION
SELECTION=$(printf '%s\n' "${!PATH_CONFIG[@]}" | dmenu -fn 'Noto Sans' -nb '#353535' -sb '#15539e' )

# Launch
if [[ -n $SELECTION ]]; then
    $TERMINAL_COMMAND $EDITOR ${PATH_CONFIG[$SELECTION]}
fi

