#!/usr/bin/bash

# Variables declarations
TERMINAL_COMMAND="alacritty --command"
EDITOR="nvim"
declare -A CONFIG_FILES

# Populate the config_files options
CONFIG_FILES[config]="${HOME}dot_files/scripts/config"
CONFIG_FILES[alacritty]="$HOME.config/alacritty/alacritty.yml"
CONFIG_FILES[i3]="$HOME.config/i3/config"
CONFIG_FILES[neovim]="$HOME.config/nvim/init.vim"

# It prints per line the indexes of $CONFIG_FILES and pipes them to dmenu
# to finally gets a $SELECTION
SELECTION=$(printf '%s\n' "${!CONFIG_FILES[@]}" | dmenu -fn 'Noto Sans' -nb '#353c4a' -sb '#43415e')

# Launch
if [[ -n $SELECTION ]]; then
    $TERMINAL_COMMAND $EDITOR ${CONFIG_FILES[$SELECTION]}
fi

