#!/usr/bin/bash

# Variables declarations

declare -A OPTION

OPTION[lock]=i3lock-fancy
OPTION[suspend]='systemctl suspend'
OPTION[hibernate]='systemctl hibernate'
OPTION[reboot]='systemctl reboot'
OPTION[poweroff]='systemctl poweroff'


# It prints per line the indexes of $OPTION
# to finally gets a $SELECTION
SELECTION=$(printf '%s\n' "${!OPTION[@]}" | dmenu -fn 'Noto Sans' -nb '#353535' -sb '#15539e' )

# Launch
if [[ -n $SELECTION ]]; then
    ${OPTION[$SELECTION]}
fi

