#!/usr/bin/bash

# Variables declarations

declare -A OPTION

OPTION[lock]=i3lock-fancy
OPTION[suspend]='systemctl suspend'
OPTION[hibernate]='systemctl hibernate'
OPTION[reboot]='systemctl reboot'
OPTION[poweroff]='systemctl poweroff'


# It prints per line the indexes of $OPTION
# to finally gets a $SELECTION
SELECTION=$(printf '%s\n' "${!OPTION[@]}" | dmenu -fn 'Noto Sans' -nf '#F8F8F2' -nb '#282A36' -sb '#6272A4' -sf '#F8F8F2' )

# Launch
if [[ -n $SELECTION ]]; then
    ${OPTION[$SELECTION]}
fi

