#!/usr/bin/bash

# If the VGA monitor is connected
if [[ -n "$(xrandr | rg 'VGA-1 connected')" ]]; then
    xrandr --output LVDS-1 --off
    xrandr --output VGA-1 --auto --primary
    i3-msg 'workspace 1'
fi
